name: admin_app
description: "A new Flutter project."
resolution: workspace
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  core_logic:
    git:
      url: https://github.com/adamcoder2/fluttercon_monorepo_example.git
      path: packages/core_logic
      ref: core_logic-v0.0.2
  design_system:
    git:
      url: https://github.com/adamcoder2/fluttercon_monorepo_example.git
      path: packages/design_system
      ref: design_system-v0.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

